---
- name: install nginx for Ubuntu
  when: ansible_os_family == "Debian"
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: install nginx for RedHat
  when: ansible_os_family == "RedHat"
  yum: 
    name: nginx
    state: present