---
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: GPG
  apt_key:
    url: "{{ gpg_url_ubuntu }}"
    state: present

- name: add docker repo
  apt_repository:
    repo: "{{ docker_repo_ubuntu }}"
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  