---
- name: install deb package from internet for debian
  when: ansible_os_family == "Debian"
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

- name: install deb package from internet for centos
  when: ansible_os_family == "RedHat"
  yum: 
    name: httpd